//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TorrentHardLinkHelper.Properties {
    using System;


    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {

        private static global::System.Resources.ResourceManager resourceMan;

        private static global::System.Globalization.CultureInfo resourceCulture;

        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }

        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TorrentHardLinkHelper.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Torrent HardLink Helper v1.0.
        /// </summary>
        public static string MainWindowTitle {
            get {
                return ResourceManager.GetString("MainWindowTitle", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to HardLinkTool.
        /// </summary>
        public static string HardLinkToolWindowTitle {
            get {
                return ResourceManager.GetString("HardLinkToolWindowTitle", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Torrent File:.
        /// </summary>
        public static string Label_TorrentFile {
            get {
                return ResourceManager.GetString("Label_TorrentFile", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Source Folder:.
        /// </summary>
        public static string Label_SourceFolder {
            get {
                return ResourceManager.GetString("Label_SourceFolder", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Output BaseFolder:.
        /// </summary>
        public static string Label_OutputBaseFolder {
            get {
                return ResourceManager.GetString("Label_OutputBaseFolder", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Source Files.
        /// </summary>
        public static string Label_SourceFiles {
            get {
                return ResourceManager.GetString("Label_SourceFiles", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Torrent Files.
        /// </summary>
        public static string Label_TorrentFiles {
            get {
                return ResourceManager.GetString("Label_TorrentFiles", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Output Folder Name:.
        /// </summary>
        public static string Label_OutputFolderName {
            get {
                return ResourceManager.GetString("Label_OutputFolderName", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to KB.
        /// </summary>
        public static string Label_KB {
            get {
                return ResourceManager.GetString("Label_KB", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Target Parent Folder.
        /// </summary>
        public static string Label_TargetParentFolder {
            get {
                return ResourceManager.GetString("Label_TargetParentFolder", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Target Folder Name.
        /// </summary>
        public static string Label_TargetFolderName {
            get {
                return ResourceManager.GetString("Label_TargetFolderName", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Select.
        /// </summary>
        public static string Button_Select {
            get {
                return ResourceManager.GetString("Button_Select", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Default.
        /// </summary>
        public static string Button_Default {
            get {
                return ResourceManager.GetString("Button_Default", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Expand All.
        /// </summary>
        public static string Button_ExpandAll {
            get {
                return ResourceManager.GetString("Button_ExpandAll", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Collapse All.
        /// </summary>
        public static string Button_CollapseAll {
            get {
                return ResourceManager.GetString("Button_CollapseAll", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Hard-Link Tool.
        /// </summary>
        public static string Button_HardLinkTool {
            get {
                return ResourceManager.GetString("Button_HardLinkTool", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Analyse.
        /// </summary>
        public static string Button_Analyse {
            get {
                return ResourceManager.GetString("Button_Analyse", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Hard-Link.
        /// </summary>
        public static string Button_HardLink {
            get {
                return ResourceManager.GetString("Button_HardLink", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Soft-Link Linux.
        /// </summary>
        public static string Button_SoftLinkLinux {
            get {
                return ResourceManager.GetString("Button_SoftLinkLinux", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Hard-Link Linux.
        /// </summary>
        public static string Button_HardLinkLinux {
            get {
                return ResourceManager.GetString("Button_HardLinkLinux", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Move Linux.
        /// </summary>
        public static string Button_MoveLinux {
            get {
                return ResourceManager.GetString("Button_MoveLinux", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Torrent Title.
        /// </summary>
        public static string OutputNameType_TorrentTitle {
            get {
                return ResourceManager.GetString("OutputNameType_TorrentTitle", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Torrent Name.
        /// </summary>
        public static string OutputNameType_TorrentName {
            get {
                return ResourceManager.GetString("OutputNameType_TorrentName", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Custom.
        /// </summary>
        public static string OutputNameType_Custom {
            get {
                return ResourceManager.GetString("OutputNameType_Custom", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Ready..
        /// </summary>
        public static string Status_Ready {
            get {
                return ResourceManager.GetString("Status_Ready", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Locating... This may take several minutes..
        /// </summary>
        public static string Status_Locating {
            get {
                return ResourceManager.GetString("Status_Locating", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Successfully located {0} of {1} file(s). Matched {2} of {3} file(s) on disk..
        /// </summary>
        public static string Status_LocateSuccess {
            get {
                return ResourceManager.GetString("Status_LocateSuccess", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Load torrent failed, exception message: {0}.
        /// </summary>
        public static string Status_LoadTorrentFailed {
            get {
                return ResourceManager.GetString("Status_LoadTorrentFailed", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Link failed, the output basefolder and the source folder must be in the same drive!.
        /// </summary>
        public static string Status_LinkFailedDifferentDrive {
            get {
                return ResourceManager.GetString("Status_LinkFailedDifferentDrive", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Linking....
        /// </summary>
        public static string Status_Linking {
            get {
                return ResourceManager.GetString("Status_Linking", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Done..
        /// </summary>
        public static string Status_Done {
            get {
                return ResourceManager.GetString("Status_Done", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Generating Linux symlink script....
        /// </summary>
        public static string Status_GeneratingLinuxSymlinkScript {
            get {
                return ResourceManager.GetString("Status_GeneratingLinuxSymlinkScript", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Done. Script saved as {0}_symlink.sh.
        /// </summary>
        public static string Status_ScriptSavedSymlink {
            get {
                return ResourceManager.GetString("Status_ScriptSavedSymlink", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Generating Linux hard link script....
        /// </summary>
        public static string Status_GeneratingLinuxHardlinkScript {
            get {
                return ResourceManager.GetString("Status_GeneratingLinuxHardlinkScript", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Done. Script saved as {0}_hardlink.sh.
        /// </summary>
        public static string Status_ScriptSavedHardlink {
            get {
                return ResourceManager.GetString("Status_ScriptSavedHardlink", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Generating Linux move script....
        /// </summary>
        public static string Status_GeneratingLinuxMoveScript {
            get {
                return ResourceManager.GetString("Status_GeneratingLinuxMoveScript", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Done. Script saved as {0}_move.sh.
        /// </summary>
        public static string Status_ScriptSavedMove {
            get {
                return ResourceManager.GetString("Status_ScriptSavedMove", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Select one torrent to open.
        /// </summary>
        public static string DialogTitle_SelectTorrent {
            get {
                return ResourceManager.GetString("DialogTitle_SelectTorrent", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Torrent Files|*.torrent.
        /// </summary>
        public static string Dialog_Filter_TorrentFiles {
            get {
                return ResourceManager.GetString("Dialog_Filter_TorrentFiles", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Confirm.
        /// </summary>
        public static string DialogTitle_Confirm {
            get {
                return ResourceManager.GetString("DialogTitle_Confirm", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to {0} files unlocated, hard link anyway?.
        /// </summary>
        public static string DialogMessage_HardLinkAnyway {
            get {
                return ResourceManager.GetString("DialogMessage_HardLinkAnyway", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to {0} files unlocated, generate script anyway?.
        /// </summary>
        public static string DialogMessage_GenerateScriptAnyway {
            get {
                return ResourceManager.GetString("DialogMessage_GenerateScriptAnyway", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to This tool helps to create a copy of a folder, the size of file below 1M will be copied, others will be hard-linked..
        /// </summary>
        public static string Description_HardLinkTool {
            get {
                return ResourceManager.GetString("Description_HardLinkTool", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Just COPY not Hard-Link when filesize is below:.
        /// </summary>
        public static string Description_CopyLimit {
            get {
                return ResourceManager.GetString("Description_CopyLimit", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to COPY.
        /// </summary>
        public static string Description_COPY {
            get {
                return ResourceManager.GetString("Description_COPY", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Just.
        /// </summary>
        public static string Description_Just {
            get {
                return ResourceManager.GetString("Description_Just", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to .torrent.
        /// </summary>
        public static string FileExtension_Torrent {
            get {
                return ResourceManager.GetString("FileExtension_Torrent", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to explorer.exe.
        /// </summary>
        public static string Process_Explorer {
            get {
                return ResourceManager.GetString("Process_Explorer", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to cmd.
        /// </summary>
        public static string Process_CMD {
            get {
                return ResourceManager.GetString("Process_CMD", resourceCulture);
            }
        }
    }
}